import os

host = os.environ.get('HOST', '192.168.0.9')

requests_config = {
    'logic_vul_identity_attack': {
        'method': 'POST',
        'url': 'http://{}:9967/auth/login-vul'.format(host),
        'headers': {'Content-Type': 'application/json'},
        'data': '{"username":"frances.goldner","debugUserId":29}',
        'name': '业务逻辑漏洞-伪造身份',
        'type': 'attack',
    },
    'logic_vul_horizontal_attack': {
        'method': 'GET',
        'url': 'http://{}:9967/api/personal/2/vul?actingUserId=27'.format(host),
        'headers': {'Content-Type': 'application/json'},
        'data': '',
        'name': '业务逻辑漏洞-水平越权',
        'type': 'attack',
    },
    'logic_vul_vertical_attack': {
        'method': 'GET',
        'url': 'http://{}:9967/api/admin/report/vul?actingUserId=27'.format(host),
        'headers': {'Content-Type': 'application/json', 'X-Client-Role': 'ADMIN'},
        'data': '',
        'name': '业务逻辑漏洞-垂直越权',
        'type': 'attack',
    },
    'logic_vul_workflow_attack': {
        'method': 'POST',
        'url': 'http://{}:9967/api/orders/5002/checkout/vul?actingUserId=27'.format(host),
        'headers': {'Content-Type': 'application/json'},
        'data': '{"clientTotal":0.01,"markAsPaid":true,"skipInventoryCheck":true}',
        'name': '业务逻辑漏洞-流程绕过',
        'type': 'attack',
    },
    'logic_vul_sms_send_attack': {
        'method': 'POST',
        'url': 'http://{}:9967/sms/send-vul'.format(host),
        'headers': {'Content-Type': 'application/json'},
        'data': '{"phoneNumber":"15134299958"}',
        'name': '业务逻辑漏洞-短信验证码回显与重放',
        'type': 'attack',
    },
    'logic_vul_sms_verify_attack': {
        'method': 'POST',
        'url': 'http://{}:9967/sms/verify-vul'.format(host),
        'headers': {'Content-Type': 'application/json'},
        'data': '{"phoneNumber":"15933988032","smsCode":"123456"}',
        'name': '业务逻辑漏洞-短信验证码未绑定手机号',
        'type': 'attack',
    },
    'logic_vul_sms_bomb_attack': {
        'method': 'POST',
        'url': 'http://{}:9967/sms/bomb-vul?phoneNumber=15134299958&batch=5'.format(host),
        'headers': {'Content-Type': 'application/json'},
        'data': '',
        'name': '业务逻辑漏洞-短信轰炸缺少频率限制',
        'type': 'attack',
    },
    'logic_vul_safe_login_normal': {
        'method': 'POST',
        'url': 'http://{}:9967/auth/login-safe'.format(host),
        'headers': {'Content-Type': 'application/json'},
        'data': '{"username":"frances.goldner","password":"3jwl2i3t6"}',
        'name': '业务逻辑漏洞-正常登录',
        'type': 'normal',
    },
    'logic_vul_info_normal': {
        'method': 'GET',
        'url': 'http://{}:9967/logic-vul/info'.format(host),
        'headers': {'Content-Type': 'application/json'},
        'data': '',
        'name': '业务逻辑漏洞-靶场信息',
        'type': 'normal',
    },
    'logic_vul_sms_safe_normal': {
        'method': 'POST',
        'url': 'http://{}:9967/sms/send-safe'.format(host),
        'headers': {'Content-Type': 'application/json'},
        'data': '{"phoneNumber":"15134299958"}',
        'name': '业务逻辑漏洞-短信验证码安全发送',
        'type': 'normal',
    },
    'logic_vul_sms_bomb_safe_normal': {
        'method': 'POST',
        'url': 'http://{}:9967/sms/bomb-safe?phoneNumber=15134299958&batch=5'.format(host),
        'headers': {'Content-Type': 'application/json'},
        'data': '',
        'name': '业务逻辑漏洞-短信发送频控对照',
        'type': 'normal',
    },
}
