FROM wushangleon/java:jdk8u112_maven as builder

COPY . /opt/js-hook
WORKDIR /opt/js-hook
RUN mvn package -DskipTests

FROM wushangleon/java:jdk8u112
COPY --from=builder /opt/js-hook/target/js-hook-1.0-SNAPSHOT.jar /opt/app.jar

EXPOSE 8080
CMD ["java", "-jar", "/opt/app.jar"]
