spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:/tmp/base_vul.db
spring.sql.init.mode=always
spring.jpa.database-platform=com.myapp.config.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none


mybatis.type-aliases-package=com.myapp.model
mybatis.mapper-locations=classpath:mapper/*.xml

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.jpa.show-sql=true
