server.port=8080
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.force-request=true
server.servlet.encoding.force-response=true
spring.messages.encoding=UTF-8
spring.datasource.url=jdbc:sqlite:./js-hook.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.datasource.hikari.maximum-pool-size=1
